# Generated by Django 4.2.7 on 2023-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Vinculo_Escolar', models.CharField(max_length=200)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Senha', models.CharField(max_length=200)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Vinculo_Escolar', models.CharField(max_length=200)),
                ('Tipo_Usuario', models.CharField(max_length=200)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Senha', models.CharField(max_length=200)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
    ]
