# Generated by Django 4.2.7 on 2024-01-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('nome', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicSearch.usuario')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicSearch.fila')),
            ],
        ),
        migrations.AddField(
            model_name='fila',
            name='alunos',
            field=models.ManyToManyField(through='medicSearch.Position', to='medicSearch.usuario'),
        ),
    ]
