# Generated by Django 4.2.7 on 2024-01-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0002_cardapio_fila_position_fila_alunos'),
    ]

    operations = [
        migrations.AddField(
            model_name='fila',
            name='tamanho',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='fila',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
