# Generated by Django 4.2.7 on 2024-01-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0004_alter_fila_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
